---
title: "CFEM dados abertos"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(editor = 'notepad')

library(tidyverse)
library(lubridate)
library(deflateBR)
library(knitr)

source('D:/Users/humberto.serna/Desktop/Anuario_Mineral_Brasileiro/Funcoes_de_Formatacao_Estilo/Funcoes_de_Formatacao_Estilo.r')
source('D:/Users/humberto.serna/Desktop/Anuario_Mineral_Brasileiro/Funcoes_de_Formatacao_Estilo/graficos_AMB.r')
source('D:/Users/humberto.serna/Documents/CSV_Data/Dados_Abertos_ANM/Funcoes_CFEM.R')

# Carregamento ----
load(file = 'D:/Users/humberto.serna/Documents/CSV_Data/cfem_BR.RData')

# _____unindo o IGP à base CFEM
IGP_DI <-
  read.table(
    file = paste(Sys.getenv("R_USER"), '/CSV_Data/IGP_DI.csv', sep = ""),
    header = TRUE,sep = ";",stringsAsFactors = FALSE, dec = ',')
IGP_DI$Data <- ymd(IGP_DI$Data)


cfem_BR <-
  left_join(cfem_BR, IGP_DI, by = c('mes.de.referencia' = "Data"))

# vetor de valores reais (DEZ2020)---- 

cfem_BR$valor.Real <- NA
for (i in 1:nrow(cfem_BR)) {
  cfem_BR$valor.Real[i] <-
    cfem_BR$valor.Recolhido.CFEM[i] * (IGP_DI[IGP_DI$Data == "2020-12-01", "IGP_DI"] /
                                         cfem_BR$IGP_DI[i])
}


# vetor de valores unitários ----


cfem_BR$valor_unitario <- 
  round(
    cfem_BR$valor.Recolhido.CFEM / cfem_BR$quantidade.Comercializada, digits = 2)


```

### 01SEM2019
```{r cfem, echo=FALSE, message=FALSE, warning=FALSE}
summary(cfem_BR[cfem_BR$semestre == '2019.1',]$valor.Recolhido.CFEM)
```
### 02SEM2019
```{r echo=FALSE, message=FALSE, warning=FALSE}
summary(cfem_BR[cfem_BR$semestre == '2019.2',]$valor.Recolhido.CFEM)
```
### 01SEM2020
```{r echo=FALSE, message=FALSE, warning=FALSE}
summary(cfem_BR[cfem_BR$semestre == '2020.1',]$valor.Recolhido.CFEM)
```
### 02SEM2020
```{r echo=FALSE, message=FALSE, warning=FALSE}
summary(cfem_BR[cfem_BR$semestre == '2020.2',]$valor.Recolhido.CFEM)
```

## ANOS
```{r echo=FALSE, message=FALSE, warning=FALSE}
FUNA_CFEM_GroupBY_Ano(anos = '2016|2017|2018|2019|2020') %>% FUNA_BARPLOT()
```

## semestres
```{r, echo=FALSE, message=FALSE, warning=FALSE}
FUNA_CFEM_GroupBY_Semestre(anos = '2016|2017|2018|2019|2020') %>% FUNA_BARPLOT()
```

## Meses nominais
```{r echo=FALSE, message=FALSE, warning=FALSE}
FUNA_CFEM_GroupBY_Mes(anos = '2016|2017|2018|2019|2020') %>% FUNA_BARPLOT()
```



## 2018 meses
```{r, echo=FALSE, message=FALSE, warning=FALSE}
FUNA_CFEM_GroupBY_Mes(anos = '2018') %>% FUNA_BARPLOT()
```


## 2019 meses
```{r echo=FALSE, message=FALSE, warning=FALSE}
FUNA_CFEM_GroupBY_Mes(anos = '2019') %>% FUNA_BARPLOT()
```


## 2020 meses
```{r echo=FALSE, message=FALSE, warning=FALSE}
FUNA_CFEM_GroupBY_Mes(anos = '2020') %>% FUNA_BARPLOT()
```


## 2020 meses em valores REAIS
```{r Meses em valores reais, echo=FALSE, message=FALSE, warning=FALSE}

FUNA_CFEM_GroupBY_Mes(anos = '2016|2017|2018|2019|2020', nominal = FALSE) %>% FUNA_BARPLOT()

```


## Maiores Empresas em cada Substância - ANO 
```{r Maiores Empresas em cada Substância - ANO, echo=FALSE}


df <-
  group_by(cfem_BR[cfem_BR$periodo %in% c(2018, 2019, 2020),],
           cpfcnpj, substancia.SCM, periodo) %>% summarise(
             "Q_Comercializada" = sum(quantidade.Comercializada),
             "CFEM" = sum(valor.Recolhido.CFEM))

```


## Extração do top 6 em cada substância 
```{r  Extração do top 6 em cada substância , echo=FALSE}

lista <- list()
i <- 1
for (ano in 2018:2020) {
  for (substancia in sort(unique(cfem_BR$substancia.SCM))) {
    lista[[i]] <-
      head(arrange(df[df$periodo == ano &
                           df$substancia.SCM == substancia,], desc(CFEM)))
    i <- i + 1
  }
}

df_1d <- 
  do.call(what = "rbind", args = lista)

kable(df_1d)

```



# _____ df_wide_maiores_empresas_ano ----
```{r maiores_empresas_ano_wide, echo=FALSE}

df_wide_maiores_empresas_ano <-
  arrange(spread(
    left_join(
      df_1d[, -4], # -Q_Comercializada
      #cpfcnpj,
      unique(cfem_BR[, c("cpfcnpj", "titular")]), 
      by = "cpfcnpj"),  
    key = periodo,
    value = CFEM
  ), desc(`2020`))[, c(1, 3, 2, 6:4)]

kable(df_wide_maiores_empresas_ano)

```



```{r}

ornamentais <- c("CALCARIO", "QUARTZITO", "DOLOMITO", "GRANITO", "ARENITO", "GRANITO ORNAMENTAL", 
"GNAISSE", "BASALTO", "ARDOSIA", "CALCARIO CALCITICO", "DIABASIO", "BASALTO P/ REVESTIMENTO", 
"GRANODIORITO", "GRANITO P/ REVESTIMENTO", "QUARTZITO SERICITICO", 
"GRANITO GNAISSICO", "MARMORE P/ REVESTIMENTO","GRANADA", "GNAISSE ORNAMENTAL")

summarise(
  group_by(
    cfem_BR[grepl(cfem_BR$substancia.SCM, pattern = "ORNAMENT") & 
              cfem_BR$periodo == 2020,], substancia.SCM),
  mean(valor_unitario, trim = 0.05))




cfem_BR[grepl(cfem_BR$substancia.SCM, pattern = "ORNAMENT") & 
              cfem_BR$periodo == 2020,]$valor_unitario %>% boxplot()




summarise(
  group_by(
    cfem_BR[cfem_BR$unidade.de.Medida %in% c("m3-> t", "m3", "m2") &
              cfem_BR$periodo == 2020 &
      cfem_BR$substancia.SCM %in% ornamentais,],
    substancia.AMB
  ),
  mean(valor_unitario, na.rm = T)
)


```



