---
title: "AMB Dados Abertos Markdown"
output: html_document
editor_options: 
  chunk_output_type: console
---
  
```{r setup, include=FALSE}

library(tidyverse)
library(kableExtra)
library(knitr)
source("D:/Users/humberto.serna/Documents/CSV_Data/Dados_Abertos_ANM/AMB_Dados_Abertos.R")

```


```{r}
# Substância - UF 

# producao_bruta
df <-
  summarise(
    group_by(.data =
               filter(.data = producao_bruta, substancia == "Manganês", ano %in% c(2015,2019)), ano, uf),
    "quantidade_Venda" = sum(quantidade.venda),
    "valor(R$)" = sum(valor.venda),
    "ROM" = sum(quantidade.producao.minerio),
    "Quantidade_Contido" = sum(quantidade.contido),
    "unidade_contido" = unique(unidade.contido))


# producao_beneficiada
df <-
  summarise(
    group_by(.data =
               filter(.data = producao_beneficiada, substancia == "Manganês", ano %in% c(2015,2019)), ano, uf),
    "quantidade_Venda" = sum(quantidade.venda),
    "valor(R$)" = sum(valor.venda),
    "quantidade.producao" = sum(quantidade.producao),
    "Quantidade_Contido" = sum(quantidade.contido),
    "unidade_contido" = unique(unidade.contido))




```




```{r vpm_ano, }

vpm_ano <- 
  select(
  producao_bruta, everything()) %>% group_by(ano) %>% summarise("VPM" = sum(valor.venda, valor.transformacao.consumo.utilizacao, valor.transferencia.transformacao.utilizacao.consumo))

kable(vpm_ano) %>% kable_styling("striped", full_width = FALSE)

```



```{r graf_vpm_ano}

ggplot(data = vpm_ano, aes(as.factor(ano), y = VPM)) + 
  geom_bar(stat = "identity")


```




```{r }
producao_bruta_SUBS <-
  spread(summarise(
    group_by(producao_bruta, substancia, ano),
    "producao.minerio" = sum(quantidade.producao.minerio)
  ),
  key = "ano",
  value = producao.minerio)

arrange(producao_bruta_SUBS, desc(`2014`)) %>% kable(format.args = list(big.mark = ".", decimal.mark = ",")) %>% kable_styling("striped", full_width = FALSE) 

```


```{r}
producao_bruta_UF <-
  spread(summarise(
    group_by(producao_bruta, uf, ano),
    "producao.minerio" = sum(quantidade.producao.minerio)
  ),
  key = "ano",
  value = producao.minerio)

arrange(producao_bruta_UF, desc(`2014`)) %>% kable(format.args = list(big.mark = ".", decimal.mark = ",")) %>% kable_styling("striped", full_width = FALSE) 
```




```{r }
producao_beneficiada_SUBS <-
  spread(summarise(
    group_by(producao_beneficiada, substancia, ano),
    "producao.minerio" = sum(quantidade.producao)
  ),
  key = "ano",
  value = producao.minerio)

arrange(producao_beneficiada_SUBS, desc(`2014`)) %>% kable(format.args = list(big.mark = ".", decimal.mark = ",")) %>% kable_styling("striped", full_width = FALSE) 

```


```{r}
producao_beneficiada_UF <-
  spread(summarise(
    group_by(
      filter(producao_beneficiada, ano == 2014), 
      uf, ano),
    "producao.minerio" = sum(quantidade.producao)
  ),
  key = "ano",
  value = producao.minerio)

arrange(producao_beneficiada_UF, desc(`2014`)) %>% kable(format.args = list(big.mark = ".", decimal.mark = ",")) %>% kable_styling("striped", full_width = FALSE) 
```






```{r}
producao_beneficiada_UF <-
  spread(summarise(
    group_by(
      filter(agua_Mineral, ano == 2014), 
      uf, ano),
    "producao.Agua_Mineral" = sum(quantidade.litros.garrafao,quantidade.litros.garrafa.plastica,quantidade.litros.garrafa.de.vidro,quantidade.litros.copo,quantidade.litros.outras.embalagens)
  ),
  key = "ano",
  value = producao.Agua_Mineral)

arrange(producao_beneficiada_UF, desc(`2014`)) %>% kable(format.args = list(big.mark = ".", decimal.mark = ",")) %>% kable_styling("striped", full_width = FALSE) 
```
